/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// --- Hand-maintained: backend {code, message} error codes (feat/plan-catalog).
// App error `code`s are NOT part of the OpenAPI document, so openapi-typescript
// never emits them — this union is curated by hand alongside the generated
// shapes. UI code branches on `ApiError.code` (lib/api.ts); these are the codes
// the plan-catalog surfaces route on. `(string & {})` keeps the union open for
// every other backend code while preserving literal autocompletion.
export type PlanErrorCode =
    | "invalid_plan"
    | "plan_name_taken"
    | "plan_not_found"
    | "plan_in_use"
    | "batch_line_limit";

export type ApiErrorCode = PlanErrorCode | (string & {});

// --- Hand-maintained: public (no-auth) landing endpoints. These live on the
// `/api/public/*` router the backend exposes for the sales landing and carry
// only marketing-safe fields — never the gate `value`/`display_value` nor the
// plan `antispam_seconds`. `price_usd` mirrors the catalog convention
// (`number | string`: Decimal serialized as a string by asyncpg/pydantic).
export interface PublicGatesResponse {
    categories: { name: string; gates: string[] }[];
    total: number;
}

export interface PublicPlansResponse {
    items: {
        name: string;
        price_usd: number | string;
        duration_days: number;
        max_lines_per_batch: number;
        credits: number;
        credits_unlimited: boolean;
        is_default: boolean;
    }[];
    total: number;
}

// --- Hand-maintained: gate-cookie vault (amazon-gate-cookie-vault, Phase 1).
// The client-facing cookie shape served by `/api/cookies` — the stored value is
// SENSITIVE and is NEVER echoed: the list/store endpoints return only
// `masked_value` (e.g. `ab••••yz`), never the raw credential. `status` is a
// Phase-2 rotation field (always `'active'` for now). Mirrors backend
// `CookieOut`.
export interface CookieOut {
    id: number;
    masked_value: string;
    status: string;
    created_at: string;
}

export interface CookieListResponse {
    items: CookieOut[];
    total: number;
}

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials, open a server-side session, set the cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session and clear the cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user; 401 when unauthenticated.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Complete the forced password change (Story 1.6, AC3).
         *
         *     Serves ONLY the forced flow: a voluntary change is out of MVP scope, hence
         *     403 when the flag is not set. Hardening from the 1.6 review:
         *
         *     - ``current_password`` (the temp password) must be proven, so a session
         *       that survived the reset's bulk revoke (a login racing the reset with the
         *       OLD credentials) cannot set the new password.
         *     - The row is re-read ``FOR UPDATE`` so a reset committing concurrently is
         *       not silently overwritten (lost update), and the flag is re-checked on
         *       the locked row.
         *     - Every OTHER session is revoked on success: a second device that logged
         *       in with the leaked temp password dies the moment the change completes.
         *       The CURRENT session stays alive (the user continues straight to their
         *       home surface — no re-login).
         */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List manageable users.
         *
         *     admin → clients only; owner → clients + admins (never other owners).
         */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create a client (admin/owner) or an admin (owner only).
         *
         *     Authorization matrix (server-enforced):
         *     - role must be 'client' or 'admin' (else forbidden).
         *     - creating 'admin' is owner-only (admin caller → forbidden).
         *     - 'client' requires a positive plan_days (else invalid_plan_days);
         *       'admin' ignores plan_days.
         */
        post: operations["create_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Remove an admin (owner-only, AC6).
         *
         *     1.3 only removes admins — a non-admin target is forbidden (client
         *     removal/block is Story 1.5; the owner can never delete an owner). The user's
         *     now-empty tenant may be left orphaned (acceptable at MVP).
         */
        delete: operations["delete_user_api_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew Plan
         * @description Renew a client's plan by adding days XOR setting a future date (AC1/AC2).
         *
         *     Validation order: target exists & is a client → exactly one mode provided →
         *     mode-specific bounds. Login re-reads the new ``expires_at`` so a renewed
         *     expired client logs in normally (AC2) — no expiry code changes here.
         */
        post: operations["renew_plan_api_admin_users__user_id__renew_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Block User
         * @description Block a client and revoke their live sessions immediately (AC3).
         */
        post: operations["block_user_api_admin_users__user_id__block_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unblock User
         * @description Unblock a client; they can log in again normally (AC4).
         */
        post: operations["unblock_user_api_admin_users__user_id__unblock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset a client's password to a one-time temp password (AC1).
         *
         *     New hash + flag + revoke-all, atomically. Revocation mirrors block (1.5):
         *     any live session dies instantly, making "log in with the temp password"
         *     (AC2's entry point) the only path forward. Works on blocked/expired
         *     clients too — their login gates still apply in the existing order.
         */
        post: operations["reset_password_api_admin_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gates
         * @description List active catalog entries (owner curation view).
         */
        get: operations["list_gates_api_admin_gates_get"];
        put?: never;
        /**
         * Create Gate
         * @description Add a gate to the catalog; duplicate ACTIVE value → 409 gate_exists.
         */
        post: operations["create_gate_api_admin_gates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/gates/{gate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Gate
         * @description Retire a gate (soft-delete, AC5): hidden from selectors, row kept.
         */
        delete: operations["delete_gate_api_admin_gates__gate_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Gate
         * @description Edit a gate's value/name/category. History is untouched — batches snapshot the string.
         */
        patch: operations["update_gate_api_admin_gates__gate_id__patch"];
        trace?: never;
    };
    "/api/admin/gate-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gate Categories
         * @description List every category, ordered by name.
         */
        get: operations["list_gate_categories_api_admin_gate_categories_get"];
        put?: never;
        /**
         * Create Gate Category
         * @description Add a category; duplicate name → 409 category_exists.
         */
        post: operations["create_gate_category_api_admin_gate_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/gate-categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Gate Category
         * @description Delete a category; ACTIVE gates still assigned → 409 category_in_use.
         *
         *     Retired gates don't block: they are reassigned to another category first
         *     (rows kept, 2.1 design). When the catalog has no other category to take
         *     them, the RESTRICT FK would fire — surfaced as the same 409.
         */
        delete: operations["delete_gate_category_api_admin_gate_categories__category_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Gate Category
         * @description Rename a category (gates keep pointing at it — nothing else moves).
         */
        patch: operations["update_gate_category_api_admin_gate_categories__category_id__patch"];
        trace?: never;
    };
    "/api/admin/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description The full pricing-plan catalog (active + retired), ordered by id.
         */
        get: operations["list_plans_api_admin_plans_get"];
        put?: never;
        /**
         * Create Plan
         * @description Add a plan to the catalog; duplicate name → 409 plan_name_taken.
         */
        post: operations["create_plan_api_admin_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Plan
         * @description Delete a plan; referenced by ≥1 client → 409 plan_in_use (retire via is_active instead).
         */
        delete: operations["delete_plan_api_admin_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Plan
         * @description Partial edit of a plan's fields; bad field → 400 invalid_plan, duplicate name → 409 plan_name_taken.
         */
        patch: operations["update_plan_api_admin_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gates
         * @description List active catalog entries (read-only — clients pick, never type).
         */
        get: operations["list_gates_api_gates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Or Append Batch
         * @description Start a new batch, or APPEND to the tenant's live one (AC 3, 10).
         *
         *     Append semantics (recorded decision): the submitted ``gate_id`` is
         *     validated for existence but its value IGNORED — new lines take the LIVE
         *     batch's gate (one lote = one gate; the UI locks the selector during a
         *     live lote). Dedup is against pending lines only: already-SENT texts may
         *     be re-queued (legacy ``/api/enviar`` semantics).
         */
        post: operations["create_or_append_batch_api_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Batch
         * @description sending → paused. Idempotent on 'paused' (two tabs): 204, no event.
         */
        post: operations["pause_batch_api_batches__batch_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Batch
         * @description paused → sending. Idempotent on 'sending': 204, no event.
         */
        post: operations["resume_batch_api_batches__batch_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Batch
         * @description sending|paused → stopped (or stopping while a line is in flight).
         *
         *     Detener acts instantly — no confirmation anywhere (AC 4). Inside ONE
         *     transaction and IN THIS ORDER: clear the queue first (a DELETE racing the
         *     worker's claim blocks on the disputed row and skips it if it landed in
         *     'sending'), THEN check for an in-flight line.
         */
        post: operations["stop_batch_api_batches__batch_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description The tenant's sessions, newest first (AC 1).
         *
         *     Flat list — the grouping by gate is presentation, done client-side.
         */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Detail
         * @description Detail with the COMPLETE Completa/Filtrada data (AC 2).
         *
         *     ``limit=None`` — the ``_SNAPSHOT_ROWS`` cap is per-reconnection only; the
         *     full data lives here (3.2's recorded promise). With no cap the totals ARE
         *     the list lengths — the count queries stay snapshot-only.
         */
        get: operations["get_session_detail_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Hard delete (AC 5) guarded by the LIVE-batch binding (AC 6).
         *
         *     The guard is "bound to a live batch", NOT ``is_active``: deleting the
         *     active session with the surface idle IS allowed (no batch to stop) — the
         *     tenant just has no active session until the next batch creates one.
         *     ``responses`` rows die via FK CASCADE; the batch history survives with
         *     ``capture_session_id`` NULL (SET NULL).
         *
         *     The lookup takes ``FOR UPDATE`` BEFORE the live-batch guard to close the
         *     TOCTOU against a concurrent ``POST /api/batches`` binding this same
         *     session (review 3-3 — the window is NOT harmless: the FK is SET NULL, so
         *     a POST committing between the guard's read and this commit would not
         *     500, it would be silently unbound, leaving a LIVE batch with no session).
         *     A concurrent binding's batch INSERT takes ``FOR KEY SHARE`` on the
         *     session row during its FK check, which conflicts with ``FOR UPDATE``:
         *     either that POST blocks and errors on the gone row, or it commits first
         *     and the guard's read here sees the live batch ⇒ 409.
         */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Session
         * @description Rename (AC 4). NO live-batch guard — recorded legacy parity
         *     ("renombrar is unguarded") — and no uniqueness: names may repeat, the
         *     stable id is the DB id. ``updated_at`` refreshes itself (onupdate).
         */
        patch: operations["rename_session_api_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Session
         * @description Download one view as ``.txt`` (Story 3.5, FR18) — generated on the fly
         *     from rows, no cache, no files on disk (architecture mandate).
         *
         *     ``view`` maps the legacy ``?tipo=completa|filtrada`` (``tipo``→``view``);
         *     the ``Literal`` validates at the edge ⇒ 422 on anything else (same
         *     treatment as every validation 422 in the project — the UI never builds an
         *     invalid view). The tenant-scoped lookup's 404 trío (unknown / foreign /
         *     out-of-int4 id) IS the AC 3 isolation — no new code, no existence leak.
         *
         *     NO live-batch guard (AC 2: works both during a live batch and on closed
         *     sessions — same lane as rename). Zero rows ⇒ 200 with an empty body
         *     (recorded decision: a 404 here would conflate "no data" with "no
         *     session"). ``PlainTextResponse`` already sets ``text/plain; charset=utf-8``;
         *     the filename in ``Content-Disposition`` is the backend's single authority.
         */
        get: operations["export_session_api_sessions__session_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Continue Session
         * @description Continuar (Story 3.4, AC 1–3): reactivate this session as the tenant's
         *     active capture session.
         *
         *     The CC dedup needs NO preloading here — it is DB-backed per
         *     ``capture_session_id`` (``add_new_cc`` + ``uq_responses_session_cc``), so
         *     reactivating the session is the whole "dedup set preserved": the next
         *     batch of the same gate binds to it via ``resolve_for_batch`` and every
         *     already-captured CC value stays deduped.
         *
         *     Guard (AC 3): ANY live batch of the tenant (sending|paused|stopping) ⇒
         *     409 ``batch_live`` — legacy parity "nueva/continuar return HTTP 409 while
         *     a batch is live or paused (`_lote_vivo`)". Unlike delete's guard it does
         *     NOT matter which session the live batch is bound to.
         *
         *     The lookup takes ``FOR UPDATE`` so it serializes with a concurrent DELETE
         *     of the same target (3.3 takes the same lock) and with another continue of
         *     the SAME target. Two continues of DIFFERENT targets (or a continue
         *     crossing a batch start) can still race into
         *     ``uq_capture_sessions_one_active_per_tenant`` at commit — mapped to 409
         *     ``session_conflict``, never a raw 500.
         *
         *     Idempotent: continuing the ALREADY-active session (surface idle) is a
         *     clean no-op in ``activate`` ⇒ 200 + emit (cheap multi-tab reconcile; the
         *     UI never offers the button on "En curso", but another tab may have
         *     activated it in between). Function name: ``continue`` is a reserved word.
         */
        post: operations["continue_session_api_sessions__session_id__continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchdog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Current latch state — the owner's alert surface polls/reads this.
         */
        get: operations["get_status_api_watchdog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchdog/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume
         * @description Clear the global pause (AC 3). Idempotent: not paused → 204, no event
         *     (two tabs / double click — the idiom of the 2.3 batch controls).
         */
        post: operations["resume_api_watchdog_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchOut */
        BatchOut: {
            /** Id */
            id: number;
            /** Gate Name */
            gate_name: string;
            /** Gate Display Value */
            gate_display_value: string;
            /** State */
            state: string;
            /** Sent */
            sent: number;
            /** Queued */
            queued: number;
            /** Failed */
            failed: number;
            /** Total */
            total: number;
            /** Appended */
            appended: boolean;
            /** Added */
            added: number;
        };
        /** CategoryListResponse */
        CategoryListResponse: {
            /** Items */
            items: components["schemas"]["CategoryOut"][];
            /** Total */
            total: number;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ChangePasswordResponse */
        ChangePasswordResponse: {
            /** Home Path */
            home_path: string;
        };
        /** CreateBatchRequest */
        CreateBatchRequest: {
            /** Text */
            text: string;
            /** Gate Id */
            gate_id: number;
        };
        /** CreateCategoryRequest */
        CreateCategoryRequest: {
            /** Name */
            name: string;
        };
        /** CreateGateRequest */
        CreateGateRequest: {
            /** Value */
            value: string;
            /** Name */
            name: string;
            /** Display Value */
            display_value: string;
            /** Category Id */
            category_id: number;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default client
             */
            role: string;
            /** Plan Id */
            plan_id?: number | null;
            /** Plan Days */
            plan_days?: number | null;
            /** Contact */
            contact?: string | null;
        };
        /** GateListResponse */
        GateListResponse: {
            /** Items */
            items: components["schemas"]["GateOut"][];
            /** Total */
            total: number;
        };
        /** GateOut */
        GateOut: {
            /** Id */
            id: number;
            /** Value */
            value: string;
            /** Name */
            name: string;
            /** Display Value */
            display_value: string;
            /** Category Id */
            category_id: number;
            /** Category Name */
            category_name: string;
            /**
             * Cookie Mode
             * @description Plain UX boolean (cookie-vault Phase 1) sourced from
             *     `gate.category.cookie_mode` — tells the cockpit when to show the cookie
             *     manager. Never carries `gate.value`.
             */
            cookie_mode?: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Tenant Id */
            tenant_id: number;
            /** Home Path */
            home_path: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Tenant Id */
            tenant_id: number;
            /** Expires At */
            expires_at?: string | null;
            plan?: components["schemas"]["PlanSummary"] | null;
        };
        /**
         * PlanSummary
         * @description The client's plan slice on /api/auth/me — null for owner/admin or a
         *     pre-catalog client (plan_id IS NULL). Powers the cockpit's max-lines guard.
         */
        PlanSummary: {
            /** Name */
            name: string;
            /** Antispam Seconds */
            antispam_seconds: number | string;
            /** Max Lines Per Batch */
            max_lines_per_batch: number;
        };
        /** PlanOut */
        PlanOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Price Usd */
            price_usd: number | string;
            /** Duration Days */
            duration_days: number;
            /** Antispam Seconds */
            antispam_seconds: number | string;
            /** Max Lines Per Batch */
            max_lines_per_batch: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlanListResponse */
        PlanListResponse: {
            /** Items */
            items: components["schemas"]["PlanOut"][];
            /** Total */
            total: number;
        };
        /** CreatePlanRequest */
        CreatePlanRequest: {
            /** Name */
            name: string;
            /** Price Usd */
            price_usd: number | string;
            /** Duration Days */
            duration_days: number;
            /** Antispam Seconds */
            antispam_seconds: number | string;
            /** Max Lines Per Batch */
            max_lines_per_batch: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * UpdatePlanRequest
         * @description Partial edit — every field optional; the patch merges over the row.
         */
        UpdatePlanRequest: {
            /** Name */
            name?: string | null;
            /** Price Usd */
            price_usd?: number | string | null;
            /** Duration Days */
            duration_days?: number | null;
            /** Antispam Seconds */
            antispam_seconds?: number | string | null;
            /** Max Lines Per Batch */
            max_lines_per_batch?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** RenameSessionRequest */
        RenameSessionRequest: {
            /** Name */
            name: string;
        };
        /** RenewPlanRequest */
        RenewPlanRequest: {
            /** Plan Id */
            plan_id?: number | null;
            /** Plan Days */
            plan_days?: number | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** ResetPasswordResponse */
        ResetPasswordResponse: {
            /** Temp Password */
            temp_password: string;
        };
        /** SessionCcRow */
        SessionCcRow: {
            /** Id */
            id: number;
            /** Text */
            text: string;
        };
        /** SessionDetailOut */
        SessionDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Gate Display Value */
            gate_display_value: string;
            /** Gate Name */
            gate_name: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Responses */
            responses: components["schemas"]["SessionResponseRow"][];
            /** Cc */
            cc: components["schemas"]["SessionCcRow"][];
            /** Responses Total */
            responses_total: number;
            /** Cc Total */
            cc_total: number;
        };
        /** SessionListResponse */
        SessionListResponse: {
            /** Items */
            items: components["schemas"]["SessionOut"][];
            /** Total */
            total: number;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Gate Display Value */
            gate_display_value: string;
            /** Gate Name */
            gate_name: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionResponseRow */
        SessionResponseRow: {
            /** Id */
            id: number;
            /** Message Id */
            message_id: number;
            /** Status */
            status: string | null;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UpdateCategoryRequest */
        UpdateCategoryRequest: {
            /** Name */
            name: string;
        };
        /** UpdateGateRequest */
        UpdateGateRequest: {
            /** Value */
            value: string;
            /** Name */
            name: string;
            /** Display Value */
            display_value: string;
            /** Category Id */
            category_id: number;
        };
        /** UserListResponse */
        UserListResponse: {
            /** Items */
            items: components["schemas"]["UserOut"][];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Tenant Id */
            tenant_id: number;
            /** Expires At */
            expires_at: string | null;
            /** Is Blocked */
            is_blocked: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchdogStatusOut */
        WatchdogStatusOut: {
            /** Paused */
            paused: boolean;
            /** Reason */
            reason: string | null;
            /** Detail */
            detail: string | null;
            /** Paused At */
            paused_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
        };
    };
    create_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_plan_api_admin_users__user_id__renew_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenewPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_user_api_admin_users__user_id__block_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_user_api_admin_users__user_id__unblock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_admin_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gates_api_admin_gates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateListResponse"];
                };
            };
        };
    };
    create_gate_api_admin_gates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_gate_api_admin_gates__gate_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_gate_api_admin_gates__gate_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gate_categories_api_admin_gate_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                };
            };
        };
    };
    create_gate_category_api_admin_gate_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_gate_category_api_admin_gate_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_gate_category_api_admin_gate_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_gates_api_gates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateListResponse"];
                };
            };
        };
    };
    list_plans_api_admin_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanListResponse"];
                };
            };
        };
    };
    create_plan_api_admin_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_admin_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_admin_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_or_append_batch_api_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_batch_api_batches__batch_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_batch_api_batches__batch_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_batch_api_batches__batch_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
        };
    };
    get_session_detail_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_session_api_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_session_api_sessions__session_id__export_get: {
        parameters: {
            query: {
                view: "completa" | "filtrada";
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_session_api_sessions__session_id__continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_watchdog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchdogStatusOut"];
                };
            };
        };
    };
    resume_api_watchdog_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
