"""gates table global catalog

Revision ID: 64cfd2bc35ff
Revises: e497cdd16d32
Create Date: 2026-06-11 20:29:28.083252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64cfd2bc35ff'
down_revision: Union[str, Sequence[str], None] = 'e497cdd16d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gates'))
    )
    op.create_index('uq_gates_value_active', 'gates', ['value'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_gates_value_active', table_name='gates', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('gates')
    # ### end Alembic commands ###
