"""auth session token, revocation, user blocked flag

Revision ID: c9296faba8c5
Revises: 282b9bd6744a
Create Date: 2026-06-11 08:25:15.683547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9296faba8c5'
down_revision: Union[str, Sequence[str], None] = '282b9bd6744a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('token', sa.String(length=64), nullable=False))
    op.add_column('auth_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_auth_sessions_token'), 'auth_sessions', ['token'], unique=True)
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_index(op.f('ix_auth_sessions_token'), table_name='auth_sessions')
    op.drop_column('auth_sessions', 'revoked_at')
    op.drop_column('auth_sessions', 'token')
    # ### end Alembic commands ###
